namespace SplatViz.Core.Analysis;

public sealed record SplatabilityCandidate(
    string Tier,
    string LayoutName,
    string ResolutionName,
    int WidthPx,
    int HeightPx,
    double CameraDistanceM,
    double PixelsPerCm,
    double BodyFrameHeightPercent,
    double BodyMarginScore,
    double NeighborParallaxScore,
    double DepthOfFieldNearM,
    double DepthOfFieldFarM,
    double DepthOfFieldSafetyScore,
    bool AcceptableFocusPass,
    double CriticalSharpnessNearM,
    double CriticalSharpnessFarM,
    double CriticalSharpnessScore,
    double FocusBoxConfidenceScore,
    double EyePlaneConfidenceScore,
    double ShadowRiskScore,
    double RigLightingInterferenceScore,
    double SplatabilityScore,
    double ProductionFeasibilityScore,
    string Verdict,
    IReadOnlyList<string> Notes);
